### ISSUE TITLE
Problems that only the English can be used for voting

### ISSUE THREAD

**Issue by ncaq** [matnad/pollmaster#12]
I am Japanese.
I searched for a bot of Discord that I can vote anonymously and came to this.
However, this has the problem that you can only use English in the voting place.

When I made a pull request to accept Japanese etc.,
Can you accept it?

**Comment by matnad** [comment]
Hi there and greetings to japan!

Yes I would love a pull request for this. However you need to make sure to only include valid japanese characters and not just all of UTF-8 as this contains "invisible" characters or characters that can't be transported over discord or the database. Currently i use the built in "isprintable" function to check if a character is accepted and I am surprised that japanese is not..

I suggest you start at the function "sanitize_string(self, string):" in poll.py line 133 which will sanitize all user input during the poll creation.

Thanks for reporting and for your help and have a nice day :)

PS: If you want to test the bot locally, you need to create a secrets.py file with the missing information shown in settings.py part2. You can ask me if you need help there.

**Comment by matnad** [comment]
#16 implements support for most UTF-8 characters. This should allow you to post polls in Japanese.
Please let me know if that is working for you so I can close this issue.

**Comment by ncaq** [comment]
great.
We can use Japanese text.
