### ISSUE TITLE
Bot is offline and private

### ISSUE THREAD

**Issue by Naxos84** [matnad/pollmaster#18]
The bot is currently offline on my server.
I kicked him and wanted to reinvite it but the bots is now private.

Is this intended?

**Comment by Jglenn12** [comment]
Please check the #announcements on the Discord. The bot is currently offline so that the developer can better shard and upgrade the hardware to deal with the increased amount of bots.

**Comment by Naxos84** [comment]
Alright I understand that.
What is the link to the discord server?
Can't find any. (Maybe I'm just not seeing it...)

**Comment by matnad** [comment]
https://discordbots.org/bot/444514223075360800
and klick on "support server". You can also track the progress of the migration here:
https://github.com/matnad/pollmaster/projects/1

**Comment by Naxos84** [comment]
Thx found it.
