### ISSUE TITLE
Problem with the pm!prefix Command

### ISSUE THREAD

**Issue by EpiccraftTV** [matnad/pollmaster#20]
I've set a custom prefix (+) but it seems to automatically reset itself back to the default prefix (pm!) after a certain amount of time, I don't exactly know how long its at most around 4 1/2 days.

**Comment by matnad** [comment]
Thanks, ill investigate and fix this

**Comment by matnad** [comment]
Was related to a database issue, and should be fixed long ago. Reopen if it happens again.

**Comment by frankiep4** [comment]
This is happening again, please help, we can't change the prefix
![Screenshot_20200125-184142](https://user-images.githubusercontent.com/33800523/73129879-6336a980-3fa2-11ea-96dd-b5cd181a6bc8.png)
