### ISSUE TITLE
Scheduled poll not activating

### ISSUE THREAD

**Issue by franklyanogre** [matnad/pollmaster#21]
I scheduled a poll for this morning to pop up at 12:01am, but it didn't activate. Am I doing something wrong? When you activate a poll, is it supposed to post in the channel? I tried to manually activate the poll, and it shows as active now on pm!show, but it never posted the poll. Am I missing something?

**Comment by matnad** [comment]
It might be that it was bound to the wrong channel so it could not post itself.
After it activates (or you active it), if it doesnt show up, you can use the pm!show <label> command to display it in any channel you like.

**Comment by franklyanogre** [comment]
Thanks. I will give that a shot.

**Comment by matnad** [comment]
fixed by #32
