### ISSUE TITLE
Using @mention in a PM causes indefinite response spam

### ISSUE THREAD

**Issue by Forge64** [matnad/pollmaster#23]
Per topic, while in a direct message with Pollmaster, used @mention, have now received a few hundred messages of "BOTPollmaster: @mention can only be used in a server text channel." with no way to stop/end them.

**Comment by matnad** [comment]
Thanks, will investigate and deploy a hotfix immediately!

**Comment by matnad** [comment]
should be fixed, let me know!

**Comment by Forge64** [comment]
It is fixed, thank you!
