### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by NinjaLynn** [matnad/pollmaster#25]
Hi, I just recently found the bot and it's amazing with all of the features. I was wondering if a couple more could be considered...

- Option to choose a different channel for the vote to populate in or the option to set a default "voting" channel. I have a private channel in my server set up for "server maintainers" that all commands are used in that I don't want to bug server members with. 

- Option to have custom reactions for polls. At the moment if you put in two custom emojis, in the poll they show up next to the A, B, C, etc reactions. 

![pollreactions](https://user-images.githubusercontent.com/13438319/61721889-94bb8780-ad69-11e9-94d6-0e8a7e16411f.JPG)

Thanks for reading and for the great bot!

**Comment by matnad** [comment]
Hey, glad you like the bot! 

- You can assign a channel where the vote is spawned if you create the vote via DM with the bot (it will ask you where to post the vote). Alternatively you can use pm!show <label> to display the vote in a different channel manually (or in multiple channels at the same time)

- This is planned for a future release!

Thanks for your feedback :)

**Comment by NinjaLynn** [comment]
Great, thanks for this info! 

Glad to hear it planned for a future release.

**Comment by dhouck** [comment]
Is there a way to specify channel from DM using `pm!cmd`?

**Comment by matnad** [comment]
Does the bot not ask for a channel if you DM pm!cmd ? It definitely should

**Comment by dhouck** [comment]
It does, but it'd be nice to be able to supply it as part of the command line instead of a wizard.

**Comment by matnad** [comment]
fixed by #32
