### ISSUE TITLE
Error message for long poll question misleading

### ISSUE THREAD

**Issue by dhouck** [matnad/pollmaster#26]
It says that the "poll name" is too long; this can easily be interpreted to mean the label instead of the question.

Additionally, 200 is *much* too short (shorter than a tweet, now); can we raise the limit there to 1000 (the actual limit on embed field length is 1024).

**Comment by matnad** [comment]
Thanks for the feedback. There is also a ~6k total embed length which we need to watch out for and I would like to avoid too long poll titles (as I consider it bad practice). But doubling the length to 400 is reasonable. I will include that in the next release.

**Comment by matnad** [comment]
I will also change the wording of the error to refer to the question
