### ISSUE TITLE
Command Line Poll Creation

### ISSUE THREAD

**Issue by Ferg633** [matnad/pollmaster#3]
It would be beneficial if a new poll could be created using the same method as in V1, by creating a single text line with all of the appropriate flags.  This would be useful for creating relatively complex polls that re-occur.  
My example is in support of Clash of Clans, after CWL, I ask my clan to vote on who should get bonus loot.  The only change in the poll each season is the number of recipients and the list of names.  all other flags stay the same, so I would be copying and pasting the majority of the <pm!new> message if I could do it in a single line instead of the wizard.

**Comment by matnad** [comment]
Feature is implemented, but requires testing before going live.
You can help testing on the support discord (Pollmaster HQ)
