### ISSUE TITLE
bot not working

### ISSUE THREAD

**Issue by dullbananas** [matnad/pollmaster#46]
I invited it to my server and typed `pm!help` but nothing happens. Discord says it's online.

**Comment by dullbananas** [comment]
sad because this seems like a very good poll bot

**Comment by BenRoe** [comment]
Same here. 😞

**Comment by benhovinga** [comment]
@dullbananas did you verify the bot has permissions to read and send in the channel you are sending the commands?

**Comment by matnad** [comment]
If the bot does not respond at all, it usually lacks the permissions to read your message or answer.
As long as you can see the bot in the user list type @Pollmaster debug to see if your permissions are correct. 

Closing this for now.
