### ISSUE TITLE
pm!prefix not returning a response

### ISSUE THREAD

**Issue by benhovinga** [matnad/pollmaster#48]
The command `pm!prefix` doesn't appear to be working at all. I get no response and the setting is not saved.

Attempted the following commands without any results.
`pm!prefix`
`pm!prefix p/`
`pm!prefix jj!`

I then run the prefix that I set and `help` to see if it works. Only `pm!` works.

**Comment by matnad** [comment]
fixed by #49

**Comment by benhovinga** [comment]
Thank you for the quick update. Usually how long before pulls with master are put into production?

**Comment by matnad** [comment]
its already live!
