### ISSUE TITLE
Suggestion aka query: One poll with multiple category answers

### ISSUE THREAD

**Issue by iNgeon** [matnad/pollmaster#75]
I am unsure if this already exists?

Basically be able to run an advanced poll with a single question but separate the answers in categories with only one answer per category allowed per user.

As example below the users answers are alphabetical and the one answer per category is implied by numerical number

- 1. What would you like for dinner ?

1. Steak A/1
2. Chicken B/1
3. Fish C/1
4. Beer D/2
5. Cool drink E/2
6. Wine F/2
7. Apple pie G/3 
8. Banana split H/3
9. Cheese cake I/3
 
Thus I would be capped to A,D,G
So something like an option 5

```
Choose the options/answers for your poll.
Either chose a preset of options or type your own options, separated by commas.

1 - :white_check_mark: :negative_squared_cross_mark:
2 - :thumbsup: :zipper_mouth: :thumbsdown:
3 - :heart_eyes: :thumbsup: :zipper_mouth: :thumbsdown: :nauseated_face:
4 - in favour, against, abstaining
5 - steak,chicken,fish | beer,cool drink, wine | apple pie, Banana split, Cheese cake
```

**Comment by eslindsey** [comment]
Doing what you want is already possible: just start three single-option polls, one for each category.

I understand your issue says "one poll" and "a single question," but why? In your example you are *actually* asking three questions:
1. What do you want for the main course?
2. What would you like to drink?
3. What would you like for desert?

**Comment by aidinism** [comment]
think about an election, for instance, vote to agree/disagree/abstention for 5 people out of 10.

**Comment by eslindsey** [comment]
@aidinism I don't understand your comment. Can you elaborate?
